# Generated by Django 5.2.5 on 2025-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=5000)),
                ("status", models.IntegerField(default=1)),
                ("user_id", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
