# Generated by Django 4.2.23 on 2025-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("role", models.CharField(max_length=10)),
                ("status", models.IntegerField(default=1)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
