"""
Django settings for qwenserver project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z__!&kgc(wqs0w%l5%vueqy%g-xs@@p1qqu=_6^2zvdt5ewclr"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 跨域问题第一处更改
    'corsheaders',
    "aichat.apps.AichatConfig",

]

MIDDLEWARE = [
    # 跨域问题第二处更改
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 403报错解决方案
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 跨域问题第三处更改允许所有来源
CORS_ALLOW_ALL_ORIGINS = True
# 或者指定允许的来源，本处暂时不设置
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:8000",
# ]


ROOT_URLCONF = "qwenserver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qwenserver.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "database_llm",  # 替换为你的数据库名
        "USER": "root",  # 替换为你的 MySQL 用户名
        "PASSWORD": "root",  # 替换为你的 MySQL 密码
        "HOST": "127.0.0.1",  # MySQL 服务器地址
        "PORT": "3306",  # MySQL 端口，默认为 3306
        "OPTIONS": {
            "charset": "utf8mb4",  # 设置字符集
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# vLLM配置信息

VLLM_CONFIG = {
    # 配置vLLM的调用地址和模型名称
    "host": "http://127.0.0.1:10222",
    "model": "111",
}

# RAG的配置信息
RAG_CONFIG = {
    # 配置知识块存储路径，这里迭代到词向量数据库的版本了，用不上
    "chunks_path": os.path.join(BASE_DIR, "chunks", "knowledges_segmented.json"),
    # 配置大模型调用地址和模型名称
    "rerank_host": "http://127.0.0.1:10220/rerank",
    "rerank_model": "/root/autodl-tmp/RAG检索增强生成/bge-reranker-base",
    # 配置RAG检索结果的阈值
    "rerank_threshold": 0.7,
    # 配置RAG检索结果的最大返回数
    "rerank_top_k": 5,
    # 配置词向量数据库ChromaDB的服务器地址
    "chroma_host": {
        "host": "127.0.0.1",  # ChromaDB 服务器地址
        "port": "58737",
    },
    # 配置词向量数据库中生成词向量模型的配置信息以及词向量库中存储表的名称
    "chroma_config": {
        "embedding_model_path": "/root/autodl-tmp/RAG检索增强生成/BAAI-bge-base-zh-v1.5",
        "collection_name": "my-collection-decimal",
    },

}